In [1]:
import numpy as np
import tensorflow as tf

In [4]:
m1 = [[1.0,2.0],
      [3.0,4.0]]

m2 = np.array([[1.0,2.0],
               [3.0,4.0]], dtype=np.float32)

m3 = tf.constant([[1.0,2.0],
                  [3.0,4.0]])

print(m1)
print(type(m1),end='\n\n')

print(m2)
print(type(m2),end='\n\n')

print(m3)
print(type(m3))

[[1.0, 2.0], [3.0, 4.0]]
<class 'list'>

[[1. 2.]
 [3. 4.]]
<class 'numpy.ndarray'>

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [5]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

print(t1,end='\n\n')

print(type(t1))
print(type(t2))
print(type(t3))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
